name: ✨ Feature Request

description: Suggest an feature or idea that you would like to see in Konect U Resume

title: "[Feature] <title>"
labels: [enhancement, v4, needs triage]
assignees: "amruthpillai"

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this feature?
      description: Please search to see if an issue already exists for the feature you requested.
      options:
        - label: Yes, I have searched the existing issues and it doesn't exist.
          required: true

  - type: textarea
    attributes:
      label: Feature Description
      description: A concise description of what feature you would like to see in Konect U Resume.
    validations:
      required: true
